### ISSUE TITLE
[7.0.0] `'Queue' refers to a value, but is being used as a type here. Did you mean 'typeof Queue'?`

### ISSUE THREAD

**Issue by charlesfries** [adopted-ember-addons/ember-file-upload#807]
Seeing this TypeScript build time error after upgrading to 7.0.0 and updating my imports:

```
node_modules/ember-file-upload/dist/upload-file-34ababbf.d.ts:12:13 - error TS2749: 'Queue' refers 
to a value, but is being used as a type here. Did you mean 'typeof Queue'?

12     queue?: Queue;
```

The error appears 6 times and comes from occurrences in `dist/upload-file-34ababbf.d.ts:`, `dist/file-queue-49328ee3.d.ts`, and `dist/interfaces-27a5f801.d.ts`.

I also am trying to import from `ember-file-upload/dist` rather than `ember-file-upload` so I can get the types. Is this not recommended?

```js
import { UploadFile } from 'ember-file-upload'; // doesn't work in TypeScript
import { UploadFile } from 'ember-file-upload/dist'; // works in TypeScript
```

```
"ember-cli": "~4.4.0",
"ember-source": "~3.28.9",
"typescript": "4.6.3",
```

**Comment by gilest** [comment]
Thanks for reporting! This should be fixed in 7.0.1
