### ISSUE TITLE
NPM bundle ember-file-upload@8.1.0 is broken

### ISSUE THREAD

**Issue by andreyfel** [adopted-ember-addons/ember-file-upload#957]
After updating `@tsconfig/ember` to v3 I started getting this error:
```
../node_modules/ember-file-upload/dist/file-queue-5aefac4a.d.ts:116:24 - error TS2307: Cannot find module 'ember-modifier/.' or its corresponding type declarations.

116     selectFile: import("ember-modifier/.").FunctionBasedModifier<{
                            ~~~~~~~~~~~~~~~~~~
```
It should probably be `import("ember-modifier")`. In the source code it is ok, so, something was broken when the build was prepared to be published to npm.

I've also checked the contents of the npm package and noticed an extra version of file-queue.d.ts and besides the files are fingerprinted although they shouldn't be.

```
ls ../node_modules/ember-file-upload/dist                                                                                                              ✔ 
_app_                                 file-queue-5839ee87.d.ts              index.d.ts                            internal.js                           test-support.js.map
components                            file-queue-5aefac4a.d.ts              index.js                              internal.js.map                       upload-file-47210fdc.d.ts
data-transfer-wrapper-17fb5832.d.ts   file-queue-5aefac4a.js                index.js.map                          services                              upload-file-reader-8076387f.d.ts
data-transfer-wrapper-17fb5832.js     file-queue-5aefac4a.js.map            interfaces-8d97937f.d.ts              test-support.d.ts                     upload-file-reader-8076387f.js
data-transfer-wrapper-17fb5832.js.map helpers                               internal.d.ts                         test-support.js                       upload-file-reader-8076387f.js.map
```

**Comment by gilest** [comment]
Hi @andreyfel – thanks for reporting.

I'm not experienced with shipping TypeScript and admittedly the TypeScript support for this project is under-tested.

I'll try to address your comments one-by-one:

> After updating @tsconfig/ember to v3 I started getting this error:

Interesting.

Are you using `ember-cli-typescript`? 
Are you using "stable" types from ember?
Are you using `@types/` definition packages?
Which `typescript` version are you running?

This addon is currently type checked _without_ `ember-cli-typescript` and `typescript` version `5.0`.

> It should probably be import("ember-modifier"). In the source code it is ok, so, something was broken when the build was 
prepared to be published to npm.

Yes that's interesting, too. It looks like the trailing `/.` is present in `7.4.0` and `8.0.0` also.

![image](https://github.com/adopted-ember-addons/ember-file-upload/assets/36919/670fe086-684c-4462-ac4a-67c8c2b338b1)

> I've also checked the contents of the npm package and noticed an extra version of file-queue.d.ts and besides the files are fingerprinted although they shouldn't be.

I think these are build-time optimisations made by rollup, not sure this is unexpected or the source of these issues.

The same basic file structure has been present since `7.0.0` when this addon was migrated to the v2 addon format (over a year ago).

**Comment by gilest** [comment]
Reproduced locally. Changes between v2 and v3 as follows:

![image](https://github.com/adopted-ember-addons/ember-file-upload/assets/36919/96be5886-bc18-45f1-a35c-c65605a4b02e)

Overriding `compilerOptions.moduleResolution` back to `"node"` in the projects `tsconfig.json` should be a temporary fix.

**Comment by gilest** [comment]
Hopefully fixed in `8.1.1`. Please let me know if it isn't
